import './globals.css'

export const metadata = {
  title: 'Egress',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-background flex flex-row items-stretch">
          {children}
        </main>
      </body>
    </html>
  )
}
